Feature/auth
supreme2302/knyaz-learning pull request #2
Opened 2021-01-19 21:29 UTC by kghislai

2021-01-27 07:03 UTC, supreme2302 requested changes

2021-01-27 07:03 UTC, supreme2302 commented on src/main/java/ru/supreme/webdemo/controller/AuthorizationController.java
> +//todo заменить get на post
Надо закрыть todo

2021-01-27 07:03 UTC, supreme2302 commented on src/main/java/ru/supreme/webdemo/controller/AuthorizationController.java
> +        return ResponseEntity.ok(user);
Мы ведь договаривались, что надо возврашать пользователя из бд.

2021-01-27 07:03 UTC, supreme2302 commented on src/main/java/ru/supreme/webdemo/controller/EmployeeController.java
> +        if (user == null) {
Не доделано

2021-02-01 20:42 UTC, closed without merging

2021-02-01 20:42 UTC, kghislai commented
:*